services:
  mongo:
    image: mongo:latest
    container_name: second-brainly-mongo
    restart: unless-stopped
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: second-brainly
    volumes:
      - mongo_data:/data/db
    command: mongod --port 27017 --bind_ip_all

  mongo-express:
    image: mongo-express:latest
    container_name: second-brainly-mongo-express
    restart: unless-stopped
    network_mode: "host"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@127.0.0.1:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: second-brainly-backend
    restart: unless-stopped
    network_mode: "host"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URL: mongodb://admin:password123@127.0.0.1:27017/second-brainly?authSource=admin
      JWT_SECRET: dev-secret-key
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./brainly-frontend
      dockerfile: Dockerfile
    container_name: second-brainly-frontend
    restart: unless-stopped
    network_mode: "host"
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
    depends_on:
      - backend
    volumes:
      - ./brainly-frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:
