
version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: second-brainly-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: second-brainly
    volumes:
      - mongo_data:/data/db
    networks:
      - second-brainly-network

  mongo-express:
    image: mongo-express:latest
    container_name: second-brainly-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
    depends_on:
      - mongo
    networks:
      - second-brainly-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: second-brainly-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URL: mongodb://admin:password123@mongo:27017/second-brainly?authSource=admin
      JWT_SECRET: dev-secret-key
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - mongo
    networks:
      - second-brainly-network
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      # Prevent node_modules from being overwritten
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./brainly-frontend
      dockerfile: Dockerfile
    container_name: second-brainly-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
    depends_on:
      - backend
    networks:
      - second-brainly-network
    volumes:
      # Mount source code for hot reload
      - ./brainly-frontend:/app
      # Prevent node_modules from being overwritten
      - frontend_node_modules:/app/node_modules
    # Keep container running even if command fails
    stdin_open: true
    tty: true

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  second-brainly-network:
    driver: bridge
